# Default blazedb configuration

# Port on which to listen for the blazedb server
# port = 9876

# Max queue size for the blazedb server commands
# max_queue_size = 100

# The logfile
# log_file = "/tmp/blazedb.log"

# Where to save data on disk
# save_file = "/tmp/blaze.dump"

# How often we need to save data on disk
# save_period = "1m"

# Debug mode (0 or 1)
# debug = 0

